# ═══════════════════════════════════════════════════════════════════════════
# LEGALPRO — VARIABLES DE ENTORNO POR SERVICIO
# Extraído de datos.txt + código fuente — 2026-06-28
# ═══════════════════════════════════════════════════════════════════════════
#
# TAGS ACTUALES (Railway):
#   frontend: brunoayala97/legalpro-frontend:1.0.3  (subido como 5.2.0)
#   node:     brunoayala97/legalpro-node:1.0.3       (subido como 5.2.0)
#   dotnet:   brunoayala97/legalpro-dotnet:1.0.3      (subido como 2.0.0)
#   owner:    NO DEPLOYADO aún
#
# NUEVO TAG: 1.0.4
# ═══════════════════════════════════════════════════════════════════════════

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  1. LEGALPRO-FRONTEND (Vite/React)                         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "VITE_NODE_API_URL=https://legalpro-node-production-34ac.up.railway.app"
echo "VITE_DOTNET_API_URL=https://legalpro-dotnet-production-5a39.up.railway.app"
echo "VITE_APK_URL=https://github.com/BrunoAyalaC/Abogacia/releases/download/v1.1.0/LegalPro-v1.1.0.apk"
echo "# PORT=3000  (solo dev, Railway asigna automáticamente)"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  2. LEGALPRO-NODE (Express/Javascript)                     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "# ── Base de datos ─────────────────────────────────────────"
echo "DATABASE_URL=postgresql://postgres:***@metro.proxy.rlwy.net:42060/railway"
echo ""
echo "# ── Autenticación ──────────────────────────────────────────"
echo "JWT_SECRET=***"
echo "JWT_EXPIRY_MINUTES=60"
echo ""
echo "# ── Gemini IA ──────────────────────────────────────────────"
echo "GEMINI_API_KEY=***"
echo ""
echo "# ── Almacenamiento S3 (legalpro-uploads Railway) ────────────"
echo "BUCKET_ACCESS_KEY_ID=\${{legalpro-uploads.ACCESS_KEY_ID}}"
echo "BUCKET_SECRET_ACCESS_KEY=\${{leg...EY}}"
echo "BUCKET_ENDPOINT=\${{legalpro-uploads.ENDPOINT}}"
echo "BUCKET_NAME=\${{legalpro-uploads.BUCKET}}"
echo "BUCKET_REGION=\${{legalpro-uploads.REGION}}"
echo ""
echo "# ── CORS ───────────────────────────────────────────────────"
echo "ALLOWED_ORIGINS=https://legalpro-frontend-production-a988.up.railway.app"
echo ""
echo "# ── Config ─────────────────────────────────────────────────"
echo "NODE_ENV=production"
echo "PORT=3001"
echo ""
echo "# ── Pagos Culqi (NUEVO) ────────────────────────────────────"
echo "CULQI_PUBLIC_KEY=pk_live_***  (pendiente de crear cuenta)"
echo "CULQI_SECRET_KEY=***  (pendiente)"
echo "# Si no se configuran, funciona en modo desarrollo (sin pago real)"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  3. LEGALPRO-DOTNET (ASP.NET Core 9)                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "# ── Conexiones ─────────────────────────────────────────────"
echo "DATABASE_URL=\${{Postgres.DATABASE_URL}}"
echo ""
echo "# ── Autenticación ──────────────────────────────────────────"
echo "JWT_SECRET=***  (misma que Node backend)"
echo ""
echo "# ── Gemini IA ──────────────────────────────────────────────"
echo "GEMINI_API_KEY=***  (misma que Node backend)"
echo ""
echo "# ── Config ─────────────────────────────────────────────────"
echo "ASPNETCORE_ENVIRONMENT=Production"
echo "ASPNETCORE_URLS=http://+:8080"
echo "ALLOWED_ORIGINS=https://legalpro-frontend-production-a988.up.railway.app"
echo "PORT=8080"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  4. LEGALPRO-OWNER (Owner Dashboard)                       ║"
echo "║     NO DEPLOYADO — Nuevo servicio                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "# ── Base de datos (misma que Node) ─────────────────────────"
echo "DATABASE_URL=\${{Postgres.DATABASE_URL}}"
echo ""
echo "# ── Autenticación ──────────────────────────────────────────"
echo "OWNER_SECRET_KEY=***  (en datos.txt)"
echo "OWNER_DECRYPTION_PHRASE=***  (min 16 caracteres)"
echo ""
echo "# ── Config ─────────────────────────────────────────────────"
echo "NODE_ENV=production"
echo "PORT=3005"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  VARIABLES NUEVAS (agregadas en esta sesión)               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "CULQI_PUBLIC_KEY=pk_***   # Frontend (PanelCreditos)"
echo "CULQI_SECRET_KEY=sk_***   # Backend Node (creditos.js)"
echo "# Culqi: https://www.culqi.com/ - crear cuenta gratis"
echo ""
echo "# Sentry (opcional, free tier 5k eventos/mes)"
echo "SENTRY_DSN=https://***@sentry.io/***"
echo "# Sin Sentry = los errores solo se ven en railway logs"
echo ""
echo "# Redis (opcional, para caché)"
echo "REDIS_URL=redis://***:6379"
echo "# Sin Redis = cache en memoria (funciona igual)"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  DEPLOY EN RAILWAY:                                        ║"
echo "║  1. Cada servicio → Variables → pegar las de arriba         ║"
echo "║  2. Settings → Deploy → Deploy Image →                     ║"
echo "║     brunoayala97/legalpro-<servicio>:1.0.4                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
